
import type { Product, Order, User } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Sulfuric Acid (H₂SO₄)',
    description: 'High-purity sulfuric acid for various industrial applications, including fertilizer production and chemical synthesis.',
    price: 350.00,
    unit: 'ton',
    factoryLocation: 'Houston, US',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Acids',
  },
  {
    id: 2,
    name: 'Sodium Hydroxide (NaOH)',
    description: 'Also known as caustic soda, used in manufacturing of pulp and paper, textiles, and soaps.',
    price: 450.50,
    unit: 'ton',
    factoryLocation: 'Ludwigshafen, DE',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Bases',
  },
  {
    id: 3,
    name: 'Ammonia (NH₃)',
    description: 'Anhydrous ammonia for agricultural use as a fertilizer and as a building block for other chemicals.',
    price: 600.00,
    unit: 'ton',
    factoryLocation: 'Dammam, SA',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Fertilizers',
  },
  {
    id: 4,
    name: 'Methanol (CH₃OH)',
    description: 'A versatile solvent and fuel, also used in the production of formaldehyde and acetic acid.',
    price: 300.75,
    unit: 'ton',
    factoryLocation: 'Shanghai, CN',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Solvents',
  },
  {
    id: 5,
    name: 'Propylene Glycol (C₃H₈O₂)',
    description: 'Industrial grade propylene glycol for use as an antifreeze, solvent, and in polymer production.',
    price: 1200.00,
    unit: 'ton',
    factoryLocation: 'Antwerp, BE',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Polymers',
  },
  {
    id: 6,
    name: 'Xylene (C₈H₁₀)',
    description: 'A common petrochemical used as a solvent in printing, rubber, and leather industries.',
    price: 950.00,
    unit: 'ton',
    factoryLocation: 'Jurong Island, SG',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Solvents',
  },
  {
    id: 7,
    name: 'Titanium Dioxide (TiO₂)',
    description: 'A white pigment used in paints, coatings, plastics, and paper for its brightness and opacity.',
    price: 2500.00,
    unit: 'ton',
    factoryLocation: 'Yanbu, SA',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Pigments',
  },
  {
    id: 8,
    name: 'Calcium Chloride (CaCl₂)',
    description: 'Used for de-icing, dust control, and as a brine for refrigeration plants.',
    price: 280.00,
    unit: 'ton',
    factoryLocation: 'Midland, US',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Salts',
  },
];

export const user: User = {
  name: 'ChemTrade Inc.',
  managerName: 'Jane Smith',
  email: 'sales@chemtrade.com',
  phone: '(987) 654-3210',
  shippingAddress: '789 Industrial Park, Chemical City, 54321',
  billingAddress: '101 Finance Tower, Commerce Bay, 09876',
  gstNumber: '27ZYXWV9876G1Z4',
  avatarUrl: 'https://placehold.co/100x100.png',
};

export const orders: Order[] = [
  {
    id: 'ORD-001',
    date: '2023-10-15',
    items: [
      { ...products[1], quantity: 10 },
      { ...products[3], quantity: 5 },
    ],
    total: 7505.00,
    status: 'Delivered',
  },
  {
    id: 'ORD-002',
    date: '2023-11-01',
    items: [{ ...products[6], quantity: 20 }],
    total: 50000.00,
    status: 'Delivered',
  },
  {
    id: 'ORD-003',
    date: '2024-01-20',
    items: [
      { ...products[0], quantity: 15 },
      { ...products[7], quantity: 50 },
    ],
    total: 19250.00,
    status: 'Processing',
  },
];
