// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApp, getApps } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "shopfront-u27pl",
  "appId": "1:1098230913014:web:c0c2424e9f4eecee5699d7",
  "storageBucket": "shopfront-u27pl.firebasestorage.app",
  "apiKey": "AIzaSyCvb2IOMLd3CvLWInHBxW7XgIrqkwmB1Mw",
  "authDomain": "shopfront-u27pl.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1098230913014"
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);

export { app, db };
